const characters = [
    {
        name: "John Doe",
        age: 30,
        gender: "Male",
        occupation: "Engineer",
        str: 70,
        con: 60,
        dex: 65,
        app: 50,
        pow: 55,
        siz: 75,
        int: 80,
        edu: 85,
        hp: 12,
        mp: 11,
        san: 60,
        luck: 50,
        moveRate: 8,
        backstory: "John grew up in a small town and developed an interest in engineering at a young age."
    },
    {
        name: "Jane Smith",
        age: 51,
        gender: "Female",
        occupation: "Doctor",
        str: 60,
        con: 70,
        dex: 75,
        app: 65,
        pow: 60,
        siz: 55,
        int: 85,
        edu: 90,
        hp: 13,
        mp: 12,
        san: 65,
        luck: 55,
        moveRate: 9,
        backstory: "Jane decided to become a doctor after witnessing the lack of medical care in her community."
    },
    {
        name: "Jane Smith",
        age: 44,
        gender: "male",
        occupation: "Doctor",
        str: 60,
        con: 70,
        dex: 75,
        app: 65,
        pow: 60,
        siz: 55,
        int: 85,
        edu: 90,
        hp: 13,
        mp: 12,
        san: 65,
        luck: 55,
        moveRate: 9,
        backstory: "Jane decided to become a doctor after witnessing the lack of medical care in her community."
    }
  ];
  
  export default characters;